spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${MYSQL_DATABASE}
    username: ${MYSQL_ROOT_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000

server:
  port: 80

logging:
  level:
    root: error
