version: "3"

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: cotl_test_zookeeper
    platform: linux/amd64
    ports:
      - "2181:2181"

  redis:
    image: redis:alpine
    container_name: cotl_test_redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6379:6379"

  database:
    image: mysql
    container_name: cotl_test_mysql
    volumes:
      - COTL_test_data:/var/lib/mysql
    env_file:
      - env/test.env
    ports:
      - "3306:3306"
    networks:
      - COTL_test_data

  kafka:
    image: wurstmeister/kafka
    container_name: cotl_test_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "Topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock
    depends_on:
      - zookeeper

volumes:
  COTL_dev_data:

networks:
  COTL_dev_data:
    driver: bridge
